version: '3.1'
services:
  tms-service:
    build: src/
    image: tms-service-image
    container_name: tms-service
    restart: on-failure
    ports:
      - "8080:8080"

    depends_on:
      - db
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tms
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=12345

  db:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=tms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345