server:
  port: 8080

jwt:
  secret: dzfgh869gdhy6zgd9jhdej
  lifetime: 10m

spring:
  config:
    use-legacy-processing: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}